version: '3'
services:
  api:
    build:
      context: .
      dockerfile: dockerfileapi
    ports:
      - "8080:8080"

  scraper:
    build:
      context: .
      dockerfile: dockerfilewebscrapper
    volumes:
      - .:/usr/src/app

  db:
    build:
      context: .
      dockerfile: dockerfiledb
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  prisma:
    build:
      context: .
      dockerfile: dockerfileprisma
    volumes:
      - .:/app/prisma
